// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANLgO08wFEnKK91ps_hgboEyyFIRg3fhM',
    appId: '1:963470251921:web:46f40eb59f935ae1072c30',
    messagingSenderId: '963470251921',
    projectId: 'makati-peso',
    authDomain: 'makati-peso.firebaseapp.com',
    storageBucket: 'makati-peso.firebasestorage.app',
    measurementId: 'G-DKKJF91TR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQgLpLkgCKo0yAjX1gU-PSdEtq-V-KU9Q',
    appId: '1:963470251921:android:34adce247f9c09ff072c30',
    messagingSenderId: '963470251921',
    projectId: 'makati-peso',
    storageBucket: 'makati-peso.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlTg7Mvqnl9HTTNMwCNNR-Tbi8nJ-lPTk',
    appId: '1:963470251921:ios:284a1751f3cd7f3b072c30',
    messagingSenderId: '963470251921',
    projectId: 'makati-peso',
    storageBucket: 'makati-peso.firebasestorage.app',
    iosBundleId: 'com.example.pesoMakatiWebsiteApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlTg7Mvqnl9HTTNMwCNNR-Tbi8nJ-lPTk',
    appId: '1:963470251921:ios:284a1751f3cd7f3b072c30',
    messagingSenderId: '963470251921',
    projectId: 'makati-peso',
    storageBucket: 'makati-peso.firebasestorage.app',
    iosBundleId: 'com.example.pesoMakatiWebsiteApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANLgO08wFEnKK91ps_hgboEyyFIRg3fhM',
    appId: '1:963470251921:web:a28cdda3592b2153072c30',
    messagingSenderId: '963470251921',
    projectId: 'makati-peso',
    authDomain: 'makati-peso.firebaseapp.com',
    storageBucket: 'makati-peso.firebasestorage.app',
    measurementId: 'G-XQREB4KKTX',
  );
}
